[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mesa_frames"
version = "0.1.0-alpha1"
description = "An extension to the Mesa framework which uses pandas/Polars DataFrames for enhanced performance"
authors = [
    { name = "Adam Amer" },
]
license = { text = "MIT" }

[tool.hatch.build.targets.wheel]
packages = ["mesa_frames"]
