[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mesa_frames"
version = "0.1.0-alpha1"
description = "An extension to the Mesa framework which uses pandas/Polars DataFrames for enhanced performance"
authors = [
    { name = "Adam Amer" },
]
license = { text = "MIT License" }

[tool.setuptools.packages.find]
where = ["mesa_frames"]
